# iPlanet instance particulars
#https or http
protocol: "https"
host: "localhost"
port: 8443
username: ""
password: ""
#text or xml
statsFormat: "xml"
#if statsFormat is text then statsPath is .perf or any custom path you configured
#if statsFormat is xml then statsPath is stats-xml or any custom path you configured
statsPath: "stats-xml"

#Proxy details if any
#proxyHost: ""
#proxyPort:
#proxyUser: ""
#proxyPassword: ""

#prefix used to show up metrics in AppDynamics
metricPrefix:  "Custom Metrics|iPlanet|"