# iPlanet instance particulars
#https or http
protocol: "https"
host: "localhost"
port: 8443
username: ""
password: ""
statsPath: ".perf"

#Proxy details if any
#proxyHost: ""
#proxyPort:
#proxyUser: ""
#proxyPassword: ""

#prefix used to show up metrics in AppDynamics
metricPrefix:  "Custom Metrics|iPlanet|"